// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package models

import (
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
)

var _ codegen.LatestVersion = codegen.Version[[0][17]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.19.0 (codegen
version v0.17.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// weaver.InstanceOf checks.

// weaver.Router checks.

// Local stub implementations.

// Client stub implementations.

// Server stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Task)(nil)

type __is_Task[T ~struct {
	weaver.AutoMarshal
	ID          string "json:\"id,omitempty\""
	Title       string "json:\"title\""
	Description string "json:\"description\""
	Completed   bool   "json:\"completed\""
}] struct{}

var _ __is_Task[Task]

func (x *Task) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Task.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.Title)
	enc.String(x.Description)
	enc.Bool(x.Completed)
}

func (x *Task) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Task.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.Title = dec.String()
	x.Description = dec.String()
	x.Completed = dec.Bool()
}
